# This file is generated by "UpdateDependencies.py" based on "https://raw.githubusercontent.com/anionDevelopment/GRYLibrary/refs/heads/main/GRYLibrary/GRYLibrary/Misc/TestKind.cs". Do not edit it manually.

from enum import Enum


class TestKind(Enum):
    # Tests that a component work like defined.
    UnitTest = 0

    # Tests that 2 (or more) components work together like defined.
    IntegrationTest = 1

    # Tests that are always skipped when committing but can be useful to do or debug a certain task/function.
    DebugHelperTest = 2

    # Tests that a specific bug does not happen anymore.
    RegressionTest = 3

    # Tests that other required systems/services used by the function under test are still available and work like specified so that the function under test is able to be working correctly.
    SystemTest = 4

    # Tests that will be done by reflection to assert a certain property for all types or all methods or all attributes in a certain scope.
    ReflectionTest = 5

    # Tests that are always skipped when committing but can be useful to demonstrate a certain thing/function.
    DemonstrationTest = 6

    # Tests that verifies a certain performance for a certain operation. Testcases of this kind often require appropriate hardware.
    PerformanceTest = 7

    # Tests that verifies that the entire communication between 2 systems is working correctly including serialization, transport and deserialization.
    EndToEndTest = 8

    # Test that only generates build-artifacts.
    GenerationTest = 9

    # Smoke testing refers to various classes of tests of systems, usually intended to determine whether they are ready for more robust testing.
    SmokeTest = 10

    def __int__(self):
        return self.value
