# This file is generated by "UpdateDependencies.py" based on "https://raw.githubusercontent.com/anionDevelopment/GRYLibrary/refs/heads/main/GRYLibrary/GRYLibrary/Misc/TestKind.cs". Do not edit it manually.

from enum import Enum


class TestKind(Enum):
    # Tests that a component work like defined.
    UnitTest = 0

    # Tests that 2 (or more) components work together like defined.
    IntegrationTest = 1

    # Tests that are not doing anything when committing but can be useful to do or debug a certain task/function.
    DebugHelperTest = 2

    # Tests that other required systems/services used by the function under test are still available and work like specified so that the function under test is able to be working correctly.
    SystemTest = 3

    # Tests that will be done by reflection to assert a certain property for all types or all methods or all attributes in a certain scope.
    ReflectionTest = 4

    # Verifies that recent changes did not break anything.
    RegressionTest = 5

    # Verifies that recent changes did not change the UI.
    VisualRegressionTest = 6

    # Tests that verifies a certain performance for a certain operation. Testcases of this kind often require appropriate hardware.
    PerformanceTest = 7

    # Tests that verifies that the entire communication between 2 systems is working correctly including serialization, transport and deserialization.
    EndToEndTest = 8

    # Test that (re)generates something.
    GenerationTest = 9

    # Verifies that a certain function is working correctly in a minimal environment with minimal dependencies.
    SmokeTest = 10

    def __int__(self):
        return self.value
