import os
import re
import shutil
import requests
from ScriptCollection.GeneralUtilities import GeneralUtilities
from ScriptCollection.TFCPS.Python.TFCPS_CodeUnitSpecific_Python import TFCPS_CodeUnitSpecific_Python_Functions,TFCPS_CodeUnitSpecific_Python_CLI

test_kind_source_url = "https://raw.githubusercontent.com/anionDevelopment/GRYLibrary/refs/heads/main/GRYLibrary/GRYLibrary/Misc/TestKind.cs"


def sync_bundled_dependency_versions():
    # The default tool-versions are maintained in '<repo>/Other/Resources/Dependencies/<tool>/Version.txt' as single
    # source of truth. Copy them into the package-resources so they are shipped with the wheel and can be read at runtime
    # (e.g. by scdownloadcachabletools in a build-image) via GeneralUtilities._internal_load_resource.
    folder_of_this_file = os.path.dirname(os.path.abspath(__file__))
    relative_paths = [
        "Dependencies/OpenAPIGenerator/Version.txt",
        "Dependencies/JRE/Version.txt",
    ]
    for relative_path in relative_paths:
        source_file = GeneralUtilities.resolve_relative_path(f"../../Other/Resources/{relative_path}", folder_of_this_file)
        target_file = GeneralUtilities.resolve_relative_path(f"../ScriptCollection/Resources/{relative_path}", folder_of_this_file)
        GeneralUtilities.assert_file_exists(source_file)
        GeneralUtilities.ensure_directory_exists(os.path.dirname(target_file))
        shutil.copyfile(source_file, target_file)

def parse_csharp_enum_entries(csharp_content: str) -> list[tuple[str, int, list[str]]]:
    # Parses the entries of a c#-enum. Returns for each entry its name, its value and the lines of its documentation-comment.
    entry_regex = re.compile(r"^(?P<name>[A-Za-z_][A-Za-z_0-9]*)\s*=\s*(?P<value>-?[0-9]+)\s*,?$")
    result: list[tuple[str, int, list[str]]] = []
    comment_lines: list[str] = []
    for raw_line in csharp_content.splitlines():
        line = raw_line.strip()
        if line.startswith("///"):
            comment_line = line[3:].strip()
            if comment_line not in ("<summary>", "</summary>", GeneralUtilities.empty_string):
                comment_lines.append(comment_line)
            continue
        if len(line) == 0:
            continue
        entry_match = entry_regex.match(line)
        if entry_match is None:
            comment_lines = []  # a line which is neither a comment nor an entry (for example the enum-declaration itself) ends the current comment-block
            continue
        result.append((entry_match.group("name"), int(entry_match.group("value")), comment_lines))
        comment_lines = []
    return result


def generate_test_kind_file_content(entries: list[tuple[str, int, list[str]]]) -> str:
    lines: list[str] = []
    lines.append(f"# This file is generated by \"{os.path.basename(__file__)}\" based on \"{test_kind_source_url}\". Do not edit it manually.")
    lines.append(GeneralUtilities.empty_string)
    lines.append("from enum import Enum")
    lines.append(GeneralUtilities.empty_string)
    lines.append(GeneralUtilities.empty_string)
    lines.append("class TestKind(Enum):")
    for index, (name, value, comment_lines) in enumerate(entries):
        if 0 < index:
            lines.append(GeneralUtilities.empty_string)
        for comment_line in comment_lines:
            lines.append(f"    # {comment_line}")
        lines.append(f"    {name} = {value}")
    lines.append(GeneralUtilities.empty_string)
    lines.append("    def __int__(self):")
    lines.append("        return self.value")
    lines.append(GeneralUtilities.empty_string)
    return "\n".join(lines)


def update_test_kinds():
    # The TestKind-enum is maintained in GRYLibrary as single source of truth. Generate a python-representation of it so that
    # products which are built using this ScriptCollection use exactly the same test-kinds (same names, same comments, same values).
    folder_of_this_file = os.path.dirname(os.path.abspath(__file__))
    target_file = GeneralUtilities.resolve_relative_path("../ScriptCollection/TestKind.py", folder_of_this_file)
    response = requests.get(test_kind_source_url, timeout=30)
    response.raise_for_status()
    entries = parse_csharp_enum_entries(response.text)
    if len(entries) == 0:
        raise ValueError(f"No enum-entries could be parsed from \"{test_kind_source_url}\".")
    GeneralUtilities.ensure_file_exists(target_file)
    GeneralUtilities.write_text_to_file(target_file, generate_test_kind_file_content(entries))


def update_dependencies():
    tf:TFCPS_CodeUnitSpecific_Python_Functions=TFCPS_CodeUnitSpecific_Python_CLI.parse(__file__)
    tf.update_dependencies()
    sync_bundled_dependency_versions()
    update_test_kinds()


if __name__ == "__main__":
    update_dependencies()
